ardalis/GuardClauses

- README.md
- src/GuardClauses.UnitTests/GuardAgainstFooExtension.cs
- src/GuardClauses.UnitTests/GuardAgainstNull.cs
- src/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
- src/GuardClauses.UnitTests/GuardFooExtension.cs
- src/GuardClauses.UnitTests/NamespaceSeparate/ExtendingGuard.cs
- src/GuardClauses/Guard.cs
This is the PR as is it was referenced in #2 
If you'd like me to clean anything up first let me know and I can make the changes. If it's easier to just change a few names or shift things around after, that works too. :)
First real PR. Not sure on etiquette. ha!
> Extendable guards

- README.md
- src/GuardClauses/Guard.cs
The typo fix is probably technically a breaking change because I believe this was pushed to Nuget already.
Likely ok?
The rest are doc and xml comment updates.
> Fix a typo and a few doc updates

- README.md
- src/GuardClauses.UnitTests/GuardAgainstNull.cs
- src/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
- src/GuardClauses.UnitTests/GuardAgainstOutOfRange.cs
- src/GuardClauses.UnitTests/NamespaceSeparate/ExtendingGuard.cs
- src/GuardClauses/Guard.cs
- src/GuardClauses/GuardClauseExtensions.cs
> Removing shortcuts from Guard and using Against extensions 

- README.md
- src/GuardClauses.UnitTests/GuardAgainstInvalidSqlDate.cs
- src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDateTime.cs
- src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInt.cs
- src/GuardClauses.UnitTests/GuardAgainstOutOfSQLDateRange.cs
- src/GuardClauses/GuardClauseExtensions.cs
* Method for guarding against passing `DateTime` values outside the valid range of `SqlDateTime` values (January 1st 1753 - December 31st 9999)
* Method for generic DateTime range guarding
* Refactor of `OutOfRange` methods to use common code
> Scott: SQL Date Guard

- src/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
- src/GuardClauses/GuardClauseExtensions.cs
- src/GuardClauses/GuardClauses.csproj
> Fix NullOrWhiteSpace Issue

- README.md
- src/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
- src/GuardClauses/GuardClauseExtensions.cs
Hey,
Decided to open this PR since I find myself creating this extension in my projects every time. 
Maybe adding to the source would help more people in this scenario.
> Added Guard.Against.NullOrEmpty for Enumerables

- src/GuardClauses/GuardClauses.csproj
Updated csproj to allow for SourceLink support.
Closes #17
> Added SourceLink Support

- azure-pipelines.yml
Following changes were made.
* Updated the CI pipelines with the new tasks
* Added conditions to skip copy and artifact publish if triggered from a PR
Closes #32
> #32: Updated the azure-pipelines.yml with the new build pipeline.

- src/GuardClauses.UnitTests/GuardAgainstDefault.cs
- src/GuardClauses/GuardClauseExtensions.cs
Added functionality requested in issue #36 as well as tests covering the new guard clause extension.
Any suggestions for improvement are greatly appreciated. 
Thanks!
-KM
> Add Guard.Against.Default and Tests

- src/GuardClauses.UnitTests/GuardAgainstDefault.cs
- src/GuardClauses/GuardClauseExtensions.cs
> Updated the Guard.Against.Default to set the parameterName of the thrown ArguementException

- src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs
- src/GuardClauses/GuardClauseExtensions.cs
#51
Add an OutOfRange method that allows to pass input as an Enum type
> Guard.Against.OutOfRange for enum accepts Enum type input

- src/GuardClauses.UnitTests/GuardAgainstNegative.cs
- src/GuardClauses/GuardClauseExtensions.cs
New Guard to protect against negative value for int, long, decimal, float and double.
#50
> Add Guard.Against.Negative

- src/Directory.Build.props
- src/GuardClauses.sln
- src/GuardClauses/Guard.cs
- src/GuardClauses/GuardClauseExtensions.cs
- src/GuardClauses/GuardClauses.csproj
> Nullable reference types

- src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDouble.cs
- src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForFloat.cs
- src/GuardClauses/GuardClauseExtensions.cs
OutOfRange overloads for double and float #61
> OutOfRange overloads for double and float

- README.md
- src/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
- src/GuardClauses/GuardClauseExtensions.cs
Added an extension NullOrEmpty that takes a nullable Guid, vallidates and returns a Guid.
Added tests for Guid NullOrEmpty.
Renamed test ThrowsGivenNullValue to ThrowsGivenNullString, and updated to nullable string.
Updated the readme.
> Guid support for NullOrEmpty

- .github/workflows/build.yml
- src/GuardClauses/GuardClauseExtensions.cs
- src/GuardClauses/GuardClauses.csproj
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs
> In Enum, OutOfRange should throw InvalidEnumArgumentException 

- src/GuardClauses/GuardClauseExtensions.cs
- test/GuardClauses.UnitTests/GuardAgainstNegative.cs
- test/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableTimeSpan.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForTimeSpan.cs
Hi,
I'd like to guard TimeSpan type like any value types.
So I add a new feature and tests.
Thanks
Please delete options that are not relevant.
> Add TimeSpan type to the GuardClauseExtensions class.

- .github/dependabot.yml
- test/GuardClauses.UnitTests/GuardClauses.UnitTests.csproj
- add `dependabot.yml` which automatically enables Dependabot's dependency versioning scanner and dependency update PRs bot by declaring dependency ecosystems and sources in the project. For dependency security vulnerabilities scanner and vulnerable dependency update PRs bot, [enable "Dependabot alerts" and "Dependabot security updates"](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates)
Resolves #86
> Resolves: Add security and versioning dependency alerts

- test/GuardClauses.UnitTests/GuardClauses.UnitTests.csproj
- add `codeql-analysis.yml` which automatically enables CodeQL code security and quality scanner. It executes on every push commit, PR, manually and every day at 8:00AM UTC. A scan check can be viewed on commits and PRs. All alerts and fix suggestion can be viewed at **Security** tab -> **Code scanning alerts** -> **CodeQL**
Resolves #95
> Resolves: Add continuous code security and quality analysis

- src/GuardClauses/GuardClauseExtensions.cs
- Add `JetBrains.Annotations.InvokerParameterNameAttribute﻿` to the codebase. 
- Add `JetBrains.Annotations.RegexPatternAttribute﻿` to the codebase.
- Fix Issue: #144 
See: https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#InvokerParameterNameAttribute
> Adds Support to `JetBrains.Annotations.InvokerParameterNameAttribute` and `RegexPatternAttribute﻿` 

- .editorconfig
- src/GuardClauses/GuardAgainstInvalidFormatExtensions.cs
- src/GuardClauses/GuardClauses.csproj
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDateTime.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDecimal.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDouble.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDecimal.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDouble.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableFloat.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableInt.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableLong.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableShort.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableTimeSpan.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForFloat.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInt.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInvalidInput.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForShort.cs
- test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForTimeSpan.cs
- test/GuardClauses.UnitTests/GuardClauses.UnitTests.csproj
- test/GuardClauses.UnitTests/NamespaceSeparate/ExtendingGuard.cs
Testing code coverage in build action
> code cleanup

- src/GuardClauses/GuardClauses.csproj
- test/GuardClauses.UnitTests/GuardAgainstExpression.cs
- test/GuardClauses.UnitTests/GuardClauses.UnitTests.csproj
This PR upgrades all of the packages to their latest versions.  It also fixes two tests that were broken in CI and locally.
> Upgrade Packages and Fix Tests
