README.md

I could have sworn I was careful about the indenting on the first pass.  Apparently not.
Now matches same indent level of first example.

Extension example formatting fix

---

src/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
src/GuardClauses.UnitTests/GuardClauses.UnitTests.csproj
src/GuardClauses/GuardClauseExtensions.cs

Same as `NullOrEmpty`, but also throws an `ArgumentException` if the string consists of nothing but whitespace characters.
Also includes:
* Updating XML comments to use `<see cref />` where possible
* Updating NuGet packages to latest version in the Unit Tests project.

Guard Clause for Null or WhiteSpace

---

src/GuardClauses/GuardClauseExtensions.cs

Hi there, thanks for your work on this nifty tool.
I noticed that the built-in `OutOfRange` guards call the `ArgumentOutOfRangeException(string paramName, string message)` constructor ([here](https://github.com/ardalis/GuardClauses/blob/master/src/GuardClauses/GuardClauseExtensions.cs#L143) and [here](https://github.com/ardalis/GuardClauses/blob/master/src/GuardClauses/GuardClauseExtensions.cs#L235)) with the parameters order reversed in relation to the [netstandard-1.1 docs](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.-ctor?view=netstandard-1.1#System_ArgumentOutOfRangeException__ctor_System_String_System_String_). That is, in the guards the `message` is passed in place of `paramName` and vice versa.
This obviously doesn't affect functionality or break …

Swapped params in ArgumentOutOfRangeException ctor

---

src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDecimal.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForShort.cs
src/GuardClauses/GuardClauseExtensions.cs

#46 
Based on the above issue, I am opening a PR to add requested out of range guards for decimal and short types. I have provided test coverage for both extensions. Also removed usings from GuardClauseExtensions.cs that are no longer needed.

Add out of range guards for short and decimal types

---

src/GuardClauses/GuardClauses.csproj

Quick change in the project properties to enable generation of XML documentation file. By default I put these files under "bin\$(Configuration)\", but it can be changed to any other location. By generating the xml file during the build, it would be included in the nuget package as well. The change won't break the build in the azure pipeline, and the package generated in the pipeline would contain the file too.
Note: By enabling the option, the compiler will produce a lot of warnings. The syntax in the comments has few errors. I will address that in a separate PR.

Intelisense not showing any xml comments. XML documentation file is missing.

---

src/GuardClauses/Guard.cs
src/GuardClauses/GuardClauseExtensions.cs

There are few small issues in the xml comments. In order to address properly the parameters, the `<see cref="input" />` should be replaced with `<paramref name="input" />`. All public constructs should contain xml comments, so short comment added in the Guard class.

Syntax issues in the xml comments.

---

src/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
src/GuardClauses/GuardClauseExtensions.cs
src/GuardClauses/GuardClauses.csproj

- Guard.Against.NegativeOrZero implemented
- Guard.Against.NegativeOrZero UnitTests added
- Fixed typo in Class Level Xml Comment.
- Changed usage of cref to paramref in xml comments, multiple locations to ensure correct parameter highlighting.
- Removed unused enumName variable from OutOfRange method.

1.3.3 - Guard.Against.NegativeOrZero + Cleanup

---

README.md
src/GuardClauses.UnitTests/GuardAgainstDefault.cs
src/GuardClauses.UnitTests/GuardAgainstNegative.cs
src/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
src/GuardClauses.UnitTests/GuardAgainstNull.cs
src/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
src/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDateTime.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDecimal.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDouble.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForFloat.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInt.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfRangeForShort.cs
src/GuardClauses.UnitTests/GuardAgainstOutOfSQLDateRange.cs
src/GuardClauses.UnitTests/GuardAgainstZero.cs
src/GuardClauses/GuardClauseExtensions.cs

Modified all guard method signatures to return the input value if the null/empty/default etc validation checks pass.
This enables a more fluent interface with usage now being two-fold:
```c#
// case 1 (previously supported usage):
public void ProcessOrder(Order order)
{
Guard.Against.Null(order, nameof(order));
// process order here
}
// case 2 (added functionality):
public class Order
{
private string _name;
private int _quantity;
private long _max;
private decimal _unitPrice;
private DateTime _dateCreated;
public Order(string name, int quantity, long max, decimal unitPrice, DateTime dateCreated)
{
_name = Guard.Against.NullOrWhiteSpace(name, nameof(name));
_quantity = Guard.Against.NegativeOrZero(quantity, nameof(quantity));
_max = Guard.Against.Zero(max, nameof(max));
_unitPrice = …
```

Guard and return in single statement

---

src/GuardClauses/GuardClauseExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs

Modify OutOfRange to include the parameter name when InvalidEnumArgumentException is thrown.

---

src/GuardClauses/Exceptions/NotFoundException.cs
src/GuardClauses/GuardClauseExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstNotFound.cs

See issue #102.
PS. Not related to this PR, tests for `Guard.Against.InvalidInput` are failing since xunit version update. Took a brief look but couldn't figure out what's the issue.

Added NotFound extension.

---

src/GuardClauses/Exceptions/NotFoundException.cs
src/GuardClauses/GuardClauseExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstNegative.cs
test/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
test/GuardClauses.UnitTests/GuardAgainstNull.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDateTime.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDecimal.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDouble.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDecimal.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDouble.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableFloat.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableInt.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableLong.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableShort.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableTimeSpan.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForFloat.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInt.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInvalidInput.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForShort.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForTimeSpan.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfSQLDateRange.cs
test/GuardClauses.UnitTests/GuardAgainstZero.cs

Hi Steve,
1. Implemented #97  as per recommendation
2. Added theory for each test class to expect the default message and custom error
3. One or two using references cleaned up
1. `InvalidEnumArgumentException` does not lend itself to accept a custom message. I did not apply the change to the `OutOfRange` methods for Enums.
2. I assumed that where another Guard is called, I do not carry the custom message across as per the example below. I feel the `ArgumentNullException` and `ArgumentException` would be slightly different concerns. :
```
Guard.Against.Null(input, parameterName);
if (input == string.Empty)
{
throw new ArgumentException(message ?? $"Required input {parameterName} was empty.", parameterName);
}
```

Custom message as optional parameter or overload

---

src/GuardClauses/GuardClauseExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstDefault.cs
test/GuardClauses.UnitTests/GuardAgainstExpression.cs
test/GuardClauses.UnitTests/GuardAgainstInvalidFormatTests.cs
test/GuardClauses.UnitTests/GuardAgainstNegative.cs
test/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
test/GuardClauses.UnitTests/GuardAgainstNull.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDateTime.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDecimal.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForDouble.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDecimal.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableDouble.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableFloat.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableInt.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableLong.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableShort.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnumerableTimeSpan.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForFloat.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForIComparable.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInt.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInvalidInput.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForShort.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForTimeSpan.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForUint.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfSQLDateRange.cs
test/GuardClauses.UnitTests/GuardAgainstZero.cs

Fixes #168 
_What was done:_
- Added tests for almost all public API functions, that test whether the custom message is correct and whether ParamName property of the thrown Arg. Exception is set correctly.
- Fixed the missing ParamName in all relevant cases (in some cases, setting ParamName was not possible due to the construction signature of the exception, e.g. InvalidEnumArgumentException).
- Some of the pre-existing tests for checking custom messages are slightly adapted, to make them a bit more consistent across the board.
_Additional notes:_
- Code updates are kept at a minimum, only focusing on the ParamName issue (a separate discussion will be started for other potential improvements)
- More than a few unit tests have been added. This was done to ensure coverage regardless of the …

Fixed Parameter Name missing in Arg. Exceptions

---

src/GuardClauses/GuardClauseExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs

Fixes #174 
What was done:
- Adapted unit tests for NullOrEmpty or NullOrWhiteSpace error messages after null check fails.
- Adapted NullOrEmpty or NullOrWhiteSpace clauses to use the custom message for the null checking.

Fixed wrong message with NullOrEmpty or NullOrWhiteSpace checks

---

src/GuardClauses/GuardAgainstNegativeExtensions.cs
src/GuardClauses/GuardAgainstNotFoundExtensions.cs
src/GuardClauses/GuardAgainstNullExtensions.cs
src/GuardClauses/GuardAgainstOutOfRangeExtensions.cs
src/GuardClauses/GuardAgainstZeroExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstDefault.cs
test/GuardClauses.UnitTests/GuardAgainstFooExtension.cs
test/GuardClauses.UnitTests/GuardAgainstNegative.cs
test/GuardClauses.UnitTests/GuardAgainstNegativeOrZero.cs
test/GuardClauses.UnitTests/GuardAgainstNotFound.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForEnum.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfSQLDateRange.cs
test/GuardClauses.UnitTests/GuardAgainstZero.cs
test/GuardClauses.UnitTests/NamespaceSeparate/ExtendingGuard.cs

Following on from #149 
I have added the attributes to a number of the other methods. There are some I have left out because they would require swapping parameter orders around and I wasn't sure how you wanted to proceed with those? The methods I skipped for this PR are:
*GuardAgainstInvalidFormExtensions.cs*
```
public static string InvalidFormat(...)
public static T InvalidInput<T>(...)
```
*GuardAgainstOutOfRangeExtensions.cs*
```
public static IEnumerable<T> OutOfRange<T>(...)
public static T OutOfRange<T>(...)
```
---
There are also a few places where I have added a `!` to stop VS moaning about null references because they relate to the `parameterName` parameter which will be given a value by the compiler so they can't be null. If my understanding of this is wrong let me know and …

Added CallerArgumentExpression and tests for more methods

---

src/GuardClauses/GuardAgainstNullExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrInvalidInput.cs

Implemented functionality mentioned in #173

Implemented NullOrInvalidInput method

---

src/GuardClauses/GuardClauses.csproj

Embed license in nuget package so that tools like https://fossa.com/ can detect the project's license when scanning dependencies in downstream applications.
Resolves #209

Embed license in nuget package 

---

src/GuardClauses/GuardAgainstEmptyOrWhiteSpaceExtensions.cs
src/GuardClauses/GuardAgainstNullExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrEmpty.cs
test/GuardClauses.UnitTests/GuardAgainstNullOrWhiteSpace.cs

Related to https://github.com/ardalis/GuardClauses/issues/220

Add NullOrEmpty and NullOrWhiteSpace overloads for ReadOnlySpan<char>

---

src/GuardClauses/GuardAgainstExpressionExtensions.cs
src/GuardClauses/GuardAgainstInvalidFormatExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstExpression.cs
test/GuardClauses.UnitTests/GuardAgainstOutOfRangeForInvalidInput.cs

PR regarding dicussion 226:
https://github.com/ardalis/GuardClauses/discussions/226
I've created the async overloads and UnitTests for it.

Created async overload for clausules that use a predicate

---

.github/workflows/build.yml
.github/workflows/comment-on-pr.yml

- Moving the PR comment to a `workflow_run` workflow that is designed for having write access, based on guidance from [GitHub Security Lab: Keeping your GitHub Actions and workflows secure Part 1](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
- Removing the unnecessary `permissions` attribute

Working through build issues for new contributors

---

.github/workflows/build.yml
.github/workflows/comment-on-pr.yml
README.md

- Minor README change to test triggering the new build structure with the `workflow_run` workflow
- Adding retention days for artifacts to keep them only for 1 day (GitHub's minimum amount)

Testing the new PR build

---

src/GuardClauses/CompilerFixes/CallerArgumentExpressionAttribute.cs
src/GuardClauses/GuardAgainstNegativeExtensions.cs
src/GuardClauses/GuardAgainstNotFoundExtensions.cs
src/GuardClauses/GuardAgainstNullExtensions.cs
src/GuardClauses/GuardAgainstOutOfRangeExtensions.cs
src/GuardClauses/GuardAgainstZeroExtensions.cs
src/GuardClauses/GuardClauses.csproj
test/GuardClauses.UnitTests/NamespaceSeparate/ExtendingGuard.cs

Fixes #291.
To test this I referenced this project directly, in a multi target project, like so:
```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
<Reference Include="Ardalis.GuardClauses">
<HintPath>..\..\..\GuardClauses\src\GuardClauses\bin\Release\net7.0\Ardalis.GuardClauses.dll</HintPath>
</Reference>
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
<Reference Include="Ardalis.GuardClauses">
<HintPath>..\..\..\GuardClauses\src\GuardClauses\bin\Release\netstandard2.1\Ardalis.GuardClauses.dll</HintPath>
</Reference>
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
<Reference Include="Ardalis.GuardClauses">
<HintPath>..\..\..\GuardClauses\src\GuardClauses\bin\Release\netstandard2.1\Ardalis.GuardClauses.dll</HintPath> …
```

291 Added backwards compatibility

---

src/GuardClauses/GuardAgainstStringLengthExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstStringTooShort.cs

StringTooShort with tests

---

src/GuardClauses/GuardAgainstOutOfRangeExtensions.cs
test/GuardClauses.UnitTests/GuardAgainstStringLengthOutOfRange.cs
test/GuardClauses.UnitTests/GuardAgainstStringOutOfRange.cs

feat: add string length out of range.

---

src/GuardClauses/GuardAgainstNullExtensions.cs

**Benchmark:** `Any()` vs `Pattern Matching` vs `TryGetNonEnumerableCount()`
https://github.com/mjebrahimi/Performance-Wars-Benchmarking-CSharp/tree/master/Enumerable-NullOrEmpty-Benchmark

Performance Improvements: NullOrEmpty check on IEnumerable<T>

---

src/GuardClauses/CompilerFixes/CallerArgumentExpressionAttribute.cs
src/GuardClauses/GuardAgainstExpressionExtensions.cs
src/GuardClauses/GuardAgainstNegativeExtensions.cs
src/GuardClauses/GuardAgainstNotFoundExtensions.cs
src/GuardClauses/GuardAgainstNullExtensions.cs
src/GuardClauses/GuardAgainstOutOfRangeExtensions.cs
src/GuardClauses/GuardAgainstStringLengthExtensions.cs
src/GuardClauses/GuardAgainstZeroExtensions.cs

The CallerArgumentExpressionAttribute also works for older versions than NETSTANDARD2_1.
So I changed the compiler directives accordingly and removed all differing signatures.

Removed different method signatures for NETFRAMEWORK and NETSTANDARD2_0

---

src/GuardClauses/GuardAgainstStringLengthExtensions.cs

Namespace and Maxmimum typo 
#340 
#341

Update for Guard Against StringLength

---

Directory.Build.props

By adding a `AnnotatedReferenceAssemblyVersion` node, it fixes the error: _"RA0001 There is more than one PackageDownload of Microsoft.NETCore.App.Ref"_
And to fix the error: _"error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again"_ on the GitHub actions, it only "injects" the TunnelVision assembly when targeting .netstandard2.0.
I found this workaround, after sneaking into other repos (for example: [Spectre.Console.csproj](https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Spectre.Console.csproj#L25)). Not quite sure if this an official solution.
Addresses #336

Add AnnotatedReferenceAssemblyVersion to fix build

---

src/GuardClauses/GuardClauses.csproj

Update to v4.6.0

---

src/GuardClauses/GuardAgainstExpressionExtensionsDeprecated.cs

Update Obsolete message to note reversal of logic.

---

src/GuardClauses/GuardClauses.csproj

Updating to v5.0

---

src/GuardClauses/GuardClauses.csproj

Set the package license to MIT explicitly in the csproj file instead of including a license file. 
With this, the license will show up directly in the about section on the nuget's page on nuget.org like this:
instead of just showing a file link like currently:
Additionally, the license is discoverable for tools like [nuget-license](https://github.com/sensslen/nuget-license) to validate licenses of dependencies in a project.

Set package license explicitly in GuardClauses.csproj with <PackageLicenseExpression>
